version: 2
updates:
  - package-ecosystem: npm
    directory: app
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
    commit-message:
      prefix: deps(frontend)
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: .github
    groups:
      github-actions-dependencies:
        patterns:
          - "*.yml"
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: deps
    cooldown:
      default-days: 7
